spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quantum
    username: root
    password: LXT980106
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
