spring:
  datasource:
    url: jdbc:mysql://rm-wz98fdnqzec28s9y6fo.mysql.rds.aliyuncs.com:3306/quantum_dev
    username: forki
    password: SEEUps000
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
