INSERT INTO user_role_groups (id, name) VALUES(1, '管理');
INSERT INTO user_role_groups (id, name) VALUES(2, '人员');
INSERT INTO user_role_groups (id, name) VALUES(3, '科研');
INSERT INTO user_role_groups (id, name) VALUES(4, '财务');
INSERT INTO user_role_groups (id, name) VALUES(5, '固定资产');
INSERT INTO user_role_groups (id, name) VALUES(6, '日常');

INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(1, 'root', '超级管理员', 1);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(2, 'export_excel', '导出Excel', 1);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(3, 'import_excel', '导入Excel', 1);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(4, 'view_hide_field', '查看其他', 1);

INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(5, 'people', '查看所有人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(6, 'people_researcher', '查看科研人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(7, 'people_student', '查看学生', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(8, 'people_teacher', '查看教辅人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(9, 'people_administration', '查看行政人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(10, 'people_postdoctoral', '查看博士后', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(11, 'people_visitor', '查看访问人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(12, 'edit_people', '修改所有人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(13, 'edit_people_researcher', '修改科研人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(14, 'edit_people_student', '修改学生', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(15, 'edit_people_teacher', '修改教辅人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(16, 'edit_people_administration', '修改行政人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(17, 'edit_people_postdoctoral', '修改博士后', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(18, 'edit_people_visitor', '修改访问人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(19, 'delete_people', '删除所有人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(20, 'delete_people_researcher', '删除科研人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(21, 'delete_people_student', '删除学生', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(22, 'delete_people_teacher', '删除教辅人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(23, 'delete_people_administration', '删除行政人员', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(24, 'delete_people_postdoctoral', '删除博士后', 2);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(25, 'delete_people_visitor', '删除访问人员', 2);

INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(26, 'research', '查看所有科研类别', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(27, 'research_paper', '查看论文', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(28, 'research_patent', '查看专利', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(29, 'research_project', '查看项目', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(30, 'research_reward', '查看获奖情况', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(31, 'edit_research', '修改所有科研类别', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(32, 'edit_research_paper', '修改论文', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(33, 'edit_research_patent', '修改专利', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(34, 'edit_research_project', '修改项目', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(35, 'edit_research_reward', '修改获奖情况', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(36, 'delete_research', '删除所有科研类别', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(37, 'delete_research_paper', '删除论文', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(38, 'delete_research_patent', '删除专利', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(39, 'delete_research_project', '删除项目', 3);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(40, 'delete_research_reward', '删除获奖情况', 3);

INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(41, 'finance', '查看所有财务类别', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(42, 'finance_expenditure', '查看所有费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(43, 'finance_expenditure_conference', '查看会议费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(44, 'finance_expenditure_consultation', '查看咨询费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(45, 'finance_expenditure_equipment', '查看设备费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(46, 'finance_expenditure_indirective', '查看间接费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(47, 'finance_expenditure_international', '查看国际合作费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(48, 'finance_expenditure_labor', '查看劳务费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(49, 'finance_expenditure_material', '查看材料费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(50, 'finance_expenditure_other', '查看其他费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(51, 'finance_expenditure_processing', '查看测试加工费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(52, 'finance_expenditure_publication', '查看出版费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(53, 'finance_expenditure_travel', '查看差旅费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(54, 'finance_social_funds', '查看公积金', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(55, 'finance_social_insurance', '查看社保', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(41, 'edit_finance', '修改所有财务类别', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(42, 'edit_finance_expenditure', '修改所有费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(43, 'edit_finance_expenditure_conference', '修改会议费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(44, 'edit_finance_expenditure_consultation', '修改咨询费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(45, 'edit_finance_expenditure_equipment', '修改设备费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(46, 'edit_finance_expenditure_indirective', '修改间接费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(47, 'edit_finance_expenditure_international', '修改国际合作费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(48, 'edit_finance_expenditure_labor', '修改劳务费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(49, 'edit_finance_expenditure_material', '修改材料费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(50, 'edit_finance_expenditure_other', '修改其他费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(51, 'edit_finance_expenditure_processing', '修改测试加工费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(52, 'edit_finance_expenditure_publication', '修改出版费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(53, 'edit_finance_expenditure_travel', '修改差旅费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(54, 'edit_finance_social_funds', '修改公积金', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(55, 'edit_finance_social_insurance', '修改社保', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(41, 'delete_finance', '删除所有财务类别', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(42, 'delete_finance_expenditure', '删除所有费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(43, 'delete_finance_expenditure_conference', '删除会议费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(44, 'delete_finance_expenditure_consultation', '删除咨询费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(45, 'delete_finance_expenditure_equipment', '删除设备费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(46, 'delete_finance_expenditure_indirective', '删除间接费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(47, 'delete_finance_expenditure_international', '删除国际合作费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(48, 'delete_finance_expenditure_labor', '删除劳务费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(49, 'delete_finance_expenditure_material', '删除材料费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(50, 'delete_finance_expenditure_other', '删除其他费用', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(51, 'delete_finance_expenditure_processing', '删除测试加工费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(52, 'delete_finance_expenditure_publication', '删除出版费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(53, 'delete_finance_expenditure_travel', '删除差旅费', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(54, 'delete_finance_social_funds', '删除公积金', 4);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(55, 'delete_finance_social_insurance', '删除社保', 4);

INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(86, 'equipment', '查看固定资产', 5);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(87, 'equipment_purchasing', '查看固定资产采购', 5);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(88, 'equipment_stock', '查看固定资产库存', 5);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(89, 'edit_equipment', '修改固定资产', 5);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(90, 'edit_equipment_purchasing', '修改固定资产采购', 5);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(91, 'edit_equipment_stock', '修改固定资产库存', 5);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(92, 'delete_equipment', '删除固定资产', 5);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(93, 'delete_equipment_purchasing', '删除固定资产采购', 5);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(94, 'delete_equipment_stock', '删除固定资产库存', 5);

INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(95, 'daily', '查看所有日常', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(96, 'daily_hosting', '查看会议举办', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(97, 'daily_report', '查看报告', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(98, 'daily_travel', '查看出行', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(99, 'daily_visit', '查看访问', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(100, 'edit_daily', '修改所有日常', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(101, 'edit_daily_hosting', '修改会议举办', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(102, 'edit_daily_report', '修改报告', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(103, 'edit_daily_travel', '修改出行', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(104, 'edit_daily_visit', '修改访问', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(105, 'delete_daily', '删除所有日常', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(106, 'delete_daily_hosting', '删除会议举办', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(107, 'delete_daily_report', '删除报告', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(108, 'delete_daily_travel', '删除出行', 6);
INSERT INTO user_role_items (id, role_key, name, group_id) VALUES(109, 'delete_daily_visit', '删除访问', 6);