package com.techncat.quantum.app.auth.annotation;

public enum ROLE {
    root,
    // 其他
    export_excel,
    import_excel,
    view_hide_field, // 隐藏字段可见，如年龄、身份证等
    // 人员
    people,
    people_inlab,
    edit_people,
    edit_people_inlab,
    delete_people,
    delete_people_inlab,
    // 科研
    research,
    research_paper,
    research_patent,
    research_project,
    research_reward,
    edit_research,
    edit_research_paper,
    edit_research_patent,
    edit_research_project,
    edit_research_reward,
    delete_research,
    delete_research_paper,
    delete_research_patent,
    delete_research_project,
    delete_research_reward,
    // 财务
    finance,
    finance_expenditure,
    finance_social_funds,
    finance_social_insurance,
    edit_finance,
    edit_finance_expenditure,
    edit_finance_social_funds,
    edit_finance_social_insurance,
    delete_finance,
    delete_finance_expenditure,
    delete_finance_social_funds,
    delete_finance_social_insurance,
    // 设备
    equipment,
    equipment_purchasing,
    equipment_stock,
    edit_equipment,
    edit_equipment_purchasing,
    edit_equipment_stock,
    delete_equipment,
    delete_equipment_purchasing,
    delete_equipment_stock,
    // 日常
    daily,
    daily_hosting,
    daily_report,
    daily_travel,
    daily_visit,
    edit_daily,
    edit_daily_hosting,
    edit_daily_report,
    edit_daily_travel,
    edit_daily_visit,
    delete_daily,
    delete_daily_hosting,
    delete_daily_report,
    delete_daily_travel,
    delete_daily_visit,
}
